[package]
name = "bevy_chess"
version = "1.0.0"
edition = "2021"

[dependencies]
chess = { path = "./crates/chess" }
chess_ai = { path = "./crates/chess_ai" }
rand = "0.8.5"
bevy = "0.8.0"

[target.'cfg(target_arch = "wasm32")'.dependencies]
web-sys = "0.3.59"
